// 演示夹具用于比较布局，不读取或声称代表本机监控数据。
const layout=document.body.dataset.layout;
document.body.classList.add(layout);
const icons={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',cpu:'M6 6h12v12H6z M9 9h6v6H9z M9 2v4 M15 2v4 M9 18v4 M15 18v4 M2 9h4 M2 15h4 M18 9h4 M18 15h4',gpu:'M3 5h18v13H3z M7 21h10 M12 18v3 M7 10h10 M7 13h6',memory:'M3 7h18v10H3z M6 10v4 M10 10v4 M14 10v4 M18 10v4 M6 17v3 M10 17v3 M14 17v3 M18 17v3',storage:'M5 3h14l3 13v5H2v-5z M2 16h20 M6 18v1 M9 18v1',power:'M3 7h16v10H3z M21 10v4 M10 8l-3 5h4l-1 3 5-6h-4l1-2',network:'M2 8c6-6 14-6 20 0 M5 12c4-4 10-4 14 0 M8 16c2-2 6-2 8 0 M12 20h.01',display:'M2 3h20v14H2z M8 21h8 M12 17v4',ports:'M12 3v17 M8 6l4-4 4 4 M12 14l6-4V7 M12 17l-6-4v-3',calendar:'M4 5h16v16H4z M4 9h16 M8 2v5 M16 2v5',moon:'M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10',refresh:'M20 7v5h-5 M4 17v-5h5 M5 7a8 8 0 0 1 13-2l2 3 M4 16l2 3a8 8 0 0 0 13-2',copy:'M9 8h12v13H9z M5 16H2V2h12v3'};
const icon=(n)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]||icons.cpu}"/></svg>`;
const modules=[
{id:'cpu',name:'CPU',sub:'Apple M4',value:18.4,unit:'%',metric:'平均负载',hint:'10 核 CPU · 4 个性能核心 + 6 个能效核心',rows:[['芯片','Apple M4'],['核心配置','4 性能核 + 6 能效核'],['指令架构','ARM64'],['核心数量','10 核']],more:[['机型标识','Mac16,1'],['信息来源','演示硬件快照']]},
{id:'gpu',name:'GPU',sub:'集成图形处理器',value:9.2,unit:'%',metric:'平均负载',hint:'10 核 GPU · 共享统一内存',rows:[['图形处理器','Apple M4'],['核心数量','10 核'],['内存形式','统一内存'],['类型','集成式']],more:[['总线','内建'],['信息来源','演示硬件快照']]},
{id:'memory',name:'内存',sub:'24 GB 统一内存',value:12.8,unit:'GB',metric:'平均使用',hint:'24 GB · CPU 与 GPU 共享',rows:[['总容量','24 GB'],['内存架构','统一内存'],['可升级','否'],['类型','系统未提供']],more:[['信息来源','演示硬件快照']]},
{id:'storage',name:'存储',sub:'内置固态硬盘',value:426,unit:'GB',metric:'已用空间快照',hint:'1 TB SSD · 内置存储',rows:[['设备','APPLE SSD'],['标称容量','1 TB'],['连接方式','PCI-Express'],['文件系统','APFS']],more:[['卷名称','Macintosh HD'],['序列号','演示中不提供']]},
{id:'power',name:'电源',sub:'内置电池',value:96,unit:'%',metric:'最大容量快照',hint:'最大容量 96% · 循环计数 83',rows:[['类型','锂离子电池'],['最大容量','96%'],['循环计数','83'],['状态','正常']],more:[['供电来源','电源适配器'],['信息来源','演示硬件快照']]},
{id:'network',name:'网络',sub:'无线网络',value:2.4,unit:'MB/s',metric:'平均下载',hint:'Wi-Fi · 当前连接信息',rows:[['接口','en0'],['连接方式','Wi-Fi'],['连接频段','5 GHz'],['硬件地址','演示中不提供']],more:[['接口状态','已连接'],['信息来源','演示连接快照']]},
{id:'display',name:'显示器',sub:'内建显示器',value:60,unit:'Hz',metric:'刷新率快照',hint:'内建 Liquid Retina XDR 显示屏',rows:[['显示器','内建显示器'],['原生分辨率','3024 × 1964'],['当前刷新率','60 Hz'],['连接','内建']],more:[['序列号','演示中不提供'],['信息来源','演示显示器快照']]},
{id:'ports',name:'接口与外设',sub:'已连接的设备',value:2,unit:'台',metric:'连接设备快照',hint:'按总线查看设备与连接信息',rows:[['USB','1 台设备'],['雷雳 / USB4','1 台设备'],['蓝牙','2 台设备'],['最近读取','14:32']],more:[['USB 设备','外接键盘'],['雷雳 / USB4 设备','扩展坞']]}
];
let active=layout==='c'?'cpu':'overview',range='7',revision=0;
const names={a:'侧栏工作台',b:'双层导航报表',c:'模块专页'};
function nav(){return `<nav class="module-nav" aria-label="报表模块">${[{id:'overview',name:'概览'},...modules].map(m=>`<a href="#${m.id}" data-module="${m.id}" class="${active===m.id?'active':''}" ${active===m.id?'aria-current="page"':''}>${icon(m.id)}<span>${m.name}</span></a>`).join('')}</nav>`}
const topMarkup=`<header class="top"><div class="top-title"><div class="brand"><span class="brandmark">h</span>HagimiMonitor</div><span class="sep"></span><span class="muted">系统详情</span></div><div class="actions"><button class="iconbutton" id="theme" aria-label="切换深浅外观" title="切换深浅外观">${icon('moon')}</button><button class="textbutton" id="refresh">${icon('refresh')}<span class="refresh-label">更新快照</span></button></div></header>`;
const filters=`<div class="filters"><span class="filter-title">历史记录 <span class="muted">/</span> <span id="range-caption">近 7 天</span></span><div class="range-controls"><div class="segments" aria-label="历史时间范围">${[['1','今日'],['7','近 7 天'],['30','近 30 天']].map(([v,t])=>`<button data-range="${v}" aria-pressed="${v==='7'}" class="${v==='7'?'selected':''}">${t}</button>`).join('')}</div><button class="date-button" id="date">${icon('calendar')}<span id="date-label">09.05 — 09.11</span><span>⌄</span></button></div></div>`;
document.querySelector('#app').innerHTML=`<div class="study"><a href="index.html">← 方案比较</a><span class="demo">${layout.toUpperCase()} · ${names[layout]} · 演示数据</span><div class="study-links"><a href="a-workspace.html" class="${layout==='a'?'current':''}">A</a><a href="b-journal.html" class="${layout==='b'?'current':''}">B</a><a href="c-focus.html" class="${layout==='c'?'current':''}">C</a></div></div><div class="shell">${topMarkup}${layout==='a'?'':`<div class="horizontal-nav">${nav()}</div>`}<div class="workspace">${layout==='a'?`<aside class="rail"><div class="eyebrow">这台 MAC</div>${nav()}<div class="rail-footer"><span class="status-dot"></span>本地设备快照<br><small>示例设备 · MacBook Pro<br>仅用于方案展示</small></div></aside>`:''}<main class="main">${filters}<div class="scroll" id="scroller"><div class="content" id="content"></div></div></main></div></div><dialog class="date-popover" id="date-dialog"><form method="dialog" id="date-form"><h3>选择历史记录范围</h3><label>开始日期<input type="date" id="date-start" value="2026-09-05" min="2026-08-01" max="2026-09-11" required></label><label>结束日期<input type="date" id="date-end" value="2026-09-11" min="2026-08-01" max="2026-09-11" required></label><p id="date-error" class="muted" role="alert"></p><div class="actions"><button type="button" class="textbutton" id="date-cancel">取消</button><button class="primary">应用</button></div></form></dialog><div id="toast" class="toast" role="status" hidden></div>`;
const computer=`<svg class="computer" viewBox="0 0 180 120" fill="none" aria-hidden="true"><rect x="24" y="10" width="132" height="87" rx="7" stroke="currentColor" stroke-width="2"/><rect x="29" y="15" width="122" height="75" rx="3" fill="currentColor" opacity=".06"/><path d="M12 101h156l-10 7H22z" fill="currentColor" opacity=".35"/><path d="M74 38h32v32H74z M80 44h20v20H80z M81 31v7 M89 31v7 M98 31v7 M81 70v7 M89 70v7 M98 70v7 M67 45h7 M67 54h7 M67 63h7 M106 45h7 M106 54h7 M106 63h7" stroke="currentColor" stroke-width="1.5"/><path d="M75 101h30" stroke="currentColor" stroke-width="3"/></svg>`;
function value(m){if(['storage','power','display','ports'].includes(m.id))return m.value;return (m.value*(range==='1'?.72:range==='30'?1.18:range==='custom'?.88:1)).toFixed(1)}
function chart(seed=1,dual=false){const width=600,height=130;function line(shift){return Array.from({length:65},(_,i)=>{const wave=Math.sin(i*.42+seed+shift)*12+Math.sin(i*1.7+seed)*6;const peak=i>33&&i<42?Math.sin((i-33)/9*Math.PI)*50:0;const f=range==='1'?.7:range==='30'?1.17:range==='custom'?.9:1;return `${i? 'L':'M'}${(i*width/64).toFixed(1)},${Math.max(8,Math.min(125,97-(wave+peak+shift*12)*f)).toFixed(1)}`}).join(' ')}const d=line(0),d2=line(2);return `<svg class="chart" viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" role="img" aria-label="${range==='1'?'今日':range==='30'?'近30天':'所选范围'}演示趋势，非本机采样">${[15,50,85,120].map(y=>`<line x1="0" x2="600" y1="${y}" y2="${y}" stroke="var(--grid)"/>`).join('')}<path d="${d} L600,130 L0,130Z" fill="var(--accent)" opacity=".07"/>${dual?`<path d="${d2}" stroke="var(--blue)" fill="none" stroke-width="1.5" opacity=".7" vector-effect="non-scaling-stroke"/>`:""}<path d="${d}" stroke="var(--accent)" fill="none" stroke-width="2" vector-effect="non-scaling-stroke"/></svg><div class="chart-labels">${(range==='1'?['00:00','06:00','12:00','18:00','23:59']:range==='30'?['08.13','08.20','08.27','09.03','09.11']:range==='custom'?['开始','25%','50%','75%','结束']:['09.05','09.07','09.09','09.10','09.11']).map(s=>`<span>${s}</span>`).join('')}</div>`}
function kpis(){return `<div class="kpis">${[modules[0],modules[1],modules[2],modules[4]].map(m=>`<a class="kpi" href="#${m.id}" data-module="${m.id}"><div class="kpi-label">${icon(m.id)}${m.name} · ${m.metric}</div><div class="kpi-value">${value(m)}<span>${m.unit}</span></div><div class="kpi-foot">${m.id==='power'?'83 次循环 · 本次快照':'所选时间范围 · 查看详情 ↗'}</div></a>`).join('')}</div>`}
function specs(m){return `<div class="spec-kicker"><span>硬件与配置 · 本次快照</span><button data-copy="${m.id}">复制信息 ↗</button></div>${m.rows.map(([k,v])=>`<div class="spec-row"><span>${k}</span><span>${v}</span></div>`).join('')}<details><summary>更多硬件信息</summary>${m.more.map(([k,v])=>`<div class="spec-row"><span>${k}</span><span>${v}</span></div>`).join('')}</details>`}
function moduleSection(m,i){const staticOnly=['storage','power','display','ports'].includes(m.id);return `<section class="module-section" id="${m.id}"><div class="module-title">${icon(m.id)}<h2>${m.name}</h2><span class="index">${String(i+1).padStart(2,'0')}</span></div><div class="module-grid"><div class="card">${specs(m)}</div><div class="card"><div class="card-head"><h3>${staticOnly?'设备信息':'运行趋势'}</h3><small>${staticOnly?'快照':'演示历史记录'}</small></div><div class="chart-total"><strong>${value(m)} ${m.unit}</strong><span>${m.metric}</span></div>${staticOnly?`<p class="muted" style="font-size:12px;line-height:1.8">${m.hint}</p><div class="note"><div class="note-number">↳</div><div>规格与状态按读取时间展示<small>历史时间筛选不会改变这份设备快照。</small></div></div>`:chart(i+1)}</div></div></section>`}
function overview(){return `<section id="overview"><div class="intro"><div><div class="eyebrow">${layout==='b'?'HAGIMI / SYSTEM REPORT':'YOUR MAC, AT A GLANCE'}</div><h1>${layout==='b'?'一份关于这台 Mac 的记录。':'这台 Mac，一目了然。'}</h1><p>硬件配置与运行记录，在这里连起来看。</p></div><div class="snapshot">快照更新于 <span class="snapshot-time">14:32</span><br>2026 年 9 月 11 日</div></div><div class="device"><div><h2>MacBook Pro</h2><p>14 英寸 · Apple M4 · 24 GB 统一内存</p><div class="device-tags"><span class="tag">macOS 15.6</span><span class="tag">1 TB 存储</span><span class="tag">本次硬件快照</span></div></div>${computer}</div>${kpis()}<div class="section-heading"><h2>运行概览</h2><small>演示历史记录</small></div><div class="overview-grid"><div class="card"><div class="card-head"><h3>负载走势</h3><div class="legend"><span><i></i>CPU</span><span><i class="blue"></i>GPU</span></div></div>${chart(4,true)}</div><div class="card"><div class="card-head"><h3>值得留意的记录</h3><small>示例</small></div><div class="note"><div class="note-number">01</div><div>周二下午出现一段负载高峰<small>结合 CPU 趋势和进程记录进一步查看。</small></div></div><div class="note"><div class="note-number">02</div><div>电池最大容量为 96%<small>这是本次快照，不随历史日期变化。</small></div></div><div class="note"><div class="note-number">03</div><div>已连接 1 台 USB 外设<small>接口与外设中可查看连接信息。</small></div></div></div></div></section>`}
function focus(m){return `<section id="${m.id}"><div class="intro"><div><div class="eyebrow">HARDWARE / ${m.id.toUpperCase()}</div><h1 class="focus-title">${m.sub}</h1><p>${m.hint}</p></div><div class="snapshot">硬件快照 <span class="snapshot-time">14:32</span><br>仅在更新快照时变化</div></div><div class="focus-caption">${icon(m.id)}<span>${m.name}详情</span><span>／</span><span>规格与运行记录</span></div><div class="focus-grid"><div class="card"><div class="card-head"><h3>${['cpu','gpu','memory','network'].includes(m.id)?'运行趋势':'本次设备状态'}</h3><div class="legend"><span><i></i>${m.name}</span></div></div><div class="chart-total"><strong>${value(m)} ${m.unit}</strong><span>${m.metric}</span></div>${['cpu','gpu','memory','network'].includes(m.id)?chart(modules.indexOf(m)+1):`<div style="padding:35px 0;line-height:2"><p>${m.hint}</p><p class="muted">设备状态为读取时的快照。<br>此处没有随日期变化的历史曲线。</p></div>`}</div><div class="card"><div class="card-head"><h3>硬件规格</h3><small>快照</small></div>${m.id==='cpu'?`<div class="mini-core" aria-label="4 个性能核心和 6 个能效核心">${'<i></i>'.repeat(10)}</div>`:''}${specs(m)}</div></div><div class="section-heading"><h2>进一步了解</h2><small>围绕 ${m.name} 的信息</small></div><div class="overview-grid"><div class="card"><div class="card-head"><h3>阅读这些数据</h3></div><p class="muted" style="line-height:1.9">${['cpu','gpu'].includes(m.id)?'负载升高表示计算任务增多。查看高峰出现的时间，再结合当时运行的应用判断原因。单次高负载不代表硬件故障。':'结合设备规格与使用场景阅读状态。缺失的系统信息保持缺失，不推断为正常或零。'}</p></div><div class="card"><div class="card-head"><h3>设备信息</h3><small>当前 Mac</small></div><div class="spec-row"><span>型号</span><span>MacBook Pro</span></div><div class="spec-row"><span>系统</span><span>macOS 15.6</span></div></div></div></section>`}
function render(){document.querySelector('#content').innerHTML=(layout==='c'?(active==='overview'?overview():focus(modules.find(m=>m.id===active))):overview()+modules.map(moduleSection).join(''))+'<footer class="footnote">HagimiMonitor · 本地系统详情<br><br>布局原型 · 所有数值为演示数据，不代表本机读数</footer>';document.querySelectorAll('.module-nav a').forEach(a=>{a.classList.toggle('active',a.dataset.module===active);if(a.dataset.module===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});updateTime()}
let toastTimer;function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,2600)}
function updateTime(){document.querySelectorAll('.snapshot-time').forEach(e=>e.textContent=revision?'14:32 · 更新 '+revision:'14:32')}
function navigate(id){if(!['overview',...modules.map(m=>m.id)].includes(id))return;active=id;history.replaceState(null,'','#'+id);if(layout==='c'){render();document.querySelector('#scroller').scrollTop=0}else{document.querySelectorAll('.module-nav a').forEach(a=>{a.classList.toggle('active',a.dataset.module===id);if(a.dataset.module===id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.getElementById(id).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}}
document.addEventListener('click',async e=>{const link=e.target.closest('[data-module]');if(link){e.preventDefault();navigate(link.dataset.module)}const r=e.target.closest('[data-range]');if(r){range=r.dataset.range;document.querySelectorAll('[data-range]').forEach(b=>{b.classList.toggle('selected',b===r);b.setAttribute('aria-pressed',String(b===r))});document.querySelector('#range-caption').textContent=range==='1'?'今日':`近 ${range} 天`;document.querySelector('#date-label').textContent=range==='1'?'09.11':range==='30'?'08.13 — 09.11':'09.05 — 09.11';document.querySelector('#date-start').value=range==='1'?'2026-09-11':range==='30'?'2026-08-13':'2026-09-05';document.querySelector('#date-end').value='2026-09-11';const y=document.querySelector('#scroller').scrollTop;render();document.querySelector('#scroller').scrollTop=y}const copy=e.target.closest('[data-copy]');if(copy){const m=modules.find(m=>m.id===copy.dataset.copy);const s=`演示数据 · ${m.name}\n`+[...m.rows,...m.more].map(([k,v])=>`${k}: ${v}`).join('\n');try{if(navigator.clipboard)await navigator.clipboard.writeText(s);else{const t=document.createElement('textarea');t.value=s;document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw Error('copy')}toast('已复制演示硬件信息')}catch{toast('当前环境无法复制，请在浏览器中打开原型。')}}});
document.querySelector('#theme').onclick=()=>{document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark'};
document.querySelector('#refresh').onclick=()=>{revision++;updateTime();toast('演示快照已更新；未采集本机数据')};
document.querySelector('#date').onclick=()=>document.querySelector('#date-dialog').showModal();
document.querySelector('#date-cancel').onclick=()=>document.querySelector('#date-dialog').close();
document.querySelector('#date-form').onsubmit=e=>{e.preventDefault();const s=document.querySelector('#date-start').value,t=document.querySelector('#date-end').value;if(s>t){document.querySelector('#date-error').textContent='结束日期不能早于开始日期。';return}range='custom';document.querySelector('#date-error').textContent='';document.querySelector('#date-caption')?.remove();document.querySelector('#range-caption').textContent='自选日期';document.querySelector('#date-label').textContent=s.slice(5).replace('-','.')+' — '+t.slice(5).replace('-','.');document.querySelectorAll('[data-range]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false')});document.querySelector('#date-dialog').close();const y=document.querySelector('#scroller').scrollTop;render();document.querySelector('#scroller').scrollTop=y};
render();if(location.hash)navigate(location.hash.slice(1));
if(layout!=='c'){let pending=false;document.querySelector('#scroller').addEventListener('scroll',()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;const top=document.querySelector('#scroller').getBoundingClientRect().top+70;let current='overview';document.querySelectorAll('#content section[id]').forEach(s=>{if(s.getBoundingClientRect().top<=top)current=s.id});active=current;document.querySelectorAll('.module-nav a').forEach(a=>{a.classList.toggle('active',a.dataset.module===current);if(a.dataset.module===current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})})},{passive:true})}
